# CONFIG FOR pyMM

outdir_ingestfile: /Users/michael/Documents/outdir
tmp_dir:
aip_storage: 
resourcespace_deliver:
pymm_scriptdir:
pymm_db:
pymm_db_user_profile:
pymm_db_name:
log_dir:


# OUTDIR_INGESTFILE=/Users/michael/Documents/outdir
# OUTDIR_INGESTXDCAM=
# OUTDIR_PAPER=
# AIP_STORAGE=/Users/michael/Documents/storage
# PODCASTDELIVER=/Users/michael/Documents/outdir
# YOUTUBEDELIVER=/Users/michael/Documents/youtube 
# TMPDIR=/Users/michael/Documents/tmpdir
# REGEX4PODCAST=
# REGEX4IA=
# DVDLABELPREFIX=
# OMNEONIP=
# OMNEONPATH=
# CUSTOM_LOG_DIR=
# LTO_INDEX_DIR=
# LOCAL_MM_DIR=/Users/michael/Github/mm
# EMAIL_FROM=
# MAKEYOUTUBE_DELIVERY_EMAIL_TO=
# MAKEBROADCAST_DELIVERY_EMAIL_TO=
# FILE_MAKER_DB=
# VOLADJUST=
# PREMIS_DB=
# SQL_ERROR_EMAIL_TO=
# PREMIS_PROFILE=
# PREMIS_NAME=
# PERCEPTUAL_HASH=
